# Generated by Django 5.1 on 2024-11-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
    ]
