# Generated by Django 5.1 on 2024-11-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_remove_bucket_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='deadline',
        ),
    ]
