# Generated by Django 5.1 on 2024-11-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_remove_bucket_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bucket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
