# Generated by Django 5.1 on 2024-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
