# Generated by Django 5.1 on 2024-12-09 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_bucket_current_amount_bucket_is_active_and_more'),
        ('expenses', '0004_expense_plaid_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buckets.bucket'),
        ),
    ]
